import type { Agent, Idea, DailyStats, CostEntry } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "ag-001",
    name: "discovery-01",
    type: "discovery",
    status: "running",
    lastHeartbeat: "2026-03-11T10:30:00Z",
    metrics: { tasksCompleted: 142, errorRate: 0.02, uptimePercent: 99.1, costUsd: 0.12 },
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "ag-002",
    name: "discovery-02",
    type: "discovery",
    status: "paused",
    lastHeartbeat: "2026-03-11T08:00:00Z",
    metrics: { tasksCompleted: 87, errorRate: 0.01, uptimePercent: 97.5, costUsd: 0.08 },
    createdAt: "2026-03-02T00:00:00Z",
  },
  {
    id: "ag-003",
    name: "validator-01",
    type: "validator",
    status: "idle",
    lastHeartbeat: "2026-03-11T09:15:00Z",
    metrics: { tasksCompleted: 23, errorRate: 0, uptimePercent: 100, costUsd: 0.05 },
    createdAt: "2026-03-03T00:00:00Z",
  },
  {
    id: "ag-004",
    name: "builder-01",
    type: "builder",
    status: "running",
    businessId: 1,
    githubRepo: "nickr/saas-analytics",
    lastHeartbeat: "2026-03-11T10:29:00Z",
    metrics: { tasksCompleted: 8, errorRate: 0.05, uptimePercent: 95.2, costUsd: 0.31 },
    createdAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "ag-005",
    name: "discovery-03",
    type: "discovery",
    status: "error",
    lastHeartbeat: "2026-03-11T06:00:00Z",
    metrics: { tasksCompleted: 56, errorRate: 0.15, uptimePercent: 82.3, costUsd: 0.06 },
    createdAt: "2026-03-04T00:00:00Z",
  },
  {
    id: "ag-006",
    name: "launcher-01",
    type: "launcher",
    status: "idle",
    lastHeartbeat: "2026-03-10T22:00:00Z",
    metrics: { tasksCompleted: 2, errorRate: 0, uptimePercent: 100, costUsd: 0.04 },
    createdAt: "2026-03-06T00:00:00Z",
  },
];

export const mockIdeas: Idea[] = [
  {
    id: 1,
    title: "AI-ассистент для ветеринарных клиник",
    description: "Автоматизация записи на приём, напоминания о вакцинации, история болезней питомцев. Рынок $30B+, софт устаревший.",
    source: "reddit",
    sourceUrl: "https://reddit.com/r/veterinary/comments/abc",
    scoreComposite: 8.4,
    verdict: "BUILD",
    verdictReason: "Вертикальный SaaS для ниши с устаревшим софтом. Высокая автономность, люди уже платят $200+/мес за плохие альтернативы.",
    status: "validated",
    discoveredAt: "2026-03-08T06:00:00Z",
    scores: { market: 8.0, automation: 9.0, pain: 8.5, competition: 8.0, willingnessToPay: 9.0, margin: 8.5, build: 7.5, timing: 8.5 },
    detail: {
      problem: "Ветеринарные клиники до сих пор используют бумажные карточки, звонки для записи и Excel для учёта. Существующие решения (Vetspire, eVetPractice) стоят $200-500/мес и перегружены функциями. Мелкие клиники (1-3 врача) не могут себе этого позволить.",
      valueProposition: "Простой AI-ассистент, который автоматизирует 80% рутины ветклиники: онлайн-запись, напоминания о вакцинации, история болезней с AI-саммари, автоматические счета. Всё за $49/мес вместо $300.",
      targetAudience: "Малые ветеринарные клиники (1-5 врачей) в США и Европе. ~60,000 клиник только в США, 70% не используют современный софт.",
      features: [
        "Онлайн-запись на приём с AI-подтверждением",
        "Автоматические SMS/email напоминания о вакцинации",
        "Электронные медкарты питомцев с AI-суммаризацией",
        "Генерация счетов и интеграция с Stripe",
        "Дашборд для владельца клиники: загрузка, доход, отзывы",
        "Мобильная версия для ветеринаров на выезде",
      ],
      techStack: ["Next.js", "PostgreSQL", "Claude API", "Stripe", "Twilio SMS", "Vercel"],
      pricing: "$49/мес (базовый) / $99/мес (про, до 5 врачей) / 14 дней free trial",
      launchSteps: [
        { step: 1, title: "Лендинг + waitlist", description: "Создать лендинг с описанием продукта, формой waitlist и SEO-оптимизацией под 'veterinary practice management software'" },
        { step: 2, title: "MVP: запись + карточки", description: "Минимальный продукт: онлайн-запись на приём + электронные карточки питомцев. Без AI — просто CRUD." },
        { step: 3, title: "AI-слой", description: "Добавить Claude для суммаризации визитов, генерации напоминаний и автоответов на частые вопросы владельцев питомцев." },
        { step: 4, title: "Биллинг", description: "Интеграция Stripe: подписки, генерация счетов для клиентов клиники, автоматические платежи." },
        { step: 5, title: "Первые клиенты", description: "Найти 5 клиник через Reddit (r/veterinary), cold email и локальные ветеринарные форумы. Предложить 3 месяца бесплатно за feedback." },
        { step: 6, title: "Product-market fit", description: "Собрать feedback, итерировать. Цель: 10 платящих клиник за 3 месяца, churn < 5%." },
      ],
      estimatedTimeline: "MVP за 3 недели, первые клиенты через 6 недель",
      estimatedCost: "$5-15/мес (хостинг + Claude API + Twilio)",
    },
  },
  {
    id: 2,
    title: "CRM для HVAC-компаний с AI-диспетчером",
    description: "Управление заявками, расписание техников, автоматические счета. Малый бизнес, 0 нормальных решений.",
    source: "hackernews",
    sourceUrl: "https://news.ycombinator.com/item?id=1",
    scoreComposite: 8.1,
    verdict: "BUILD",
    verdictReason: "Blue ocean ниша. Подрядчики готовы платить $49-99/мес. Минимальная конкуренция в вертикали.",
    status: "validated",
    discoveredAt: "2026-03-07T07:00:00Z",
    scores: { market: 7.5, automation: 8.5, pain: 9.0, competition: 9.0, willingnessToPay: 8.5, margin: 7.5, build: 7.0, timing: 8.0 },
    detail: {
      problem: "HVAC-компании (отопление, вентиляция, кондиционирование) управляют заявками через бумагу, WhatsApp и Excel. Техники забывают о визитах, счета выставляются с задержкой на недели. Крупные CRM (ServiceTitan) стоят $500+/мес — малым компаниям не по карману.",
      valueProposition: "Простая CRM с AI-диспетчером: принимает заявки, распределяет по техникам, отслеживает выполнение, генерирует счета автоматически. $49/мес вместо $500.",
      targetAudience: "Малые HVAC-компании (1-10 техников) в США. ~100,000 компаний, 80% используют бумагу или Excel.",
      features: [
        "Приём заявок через веб-форму, телефон (Twilio) и email",
        "AI-диспетчер: автоматическое распределение заявок по техникам",
        "Мобильное приложение для техников: маршруты, чеклисты, фото",
        "Автоматическая генерация счетов после завершения работы",
        "Дашборд владельца: доход, загрузка техников, рейтинг клиентов",
        "SMS-уведомления клиентам: 'Техник будет через 30 минут'",
      ],
      techStack: ["Next.js", "Supabase", "Claude API", "Stripe", "Twilio", "React Native"],
      pricing: "$49/мес (до 5 техников) / $99/мес (до 15 техников) / 14 дней free trial",
      launchSteps: [
        { step: 1, title: "Лендинг + waitlist", description: "Лендинг под ключевые слова 'hvac scheduling software', 'hvac dispatch software'. Форма waitlist." },
        { step: 2, title: "MVP: заявки + расписание", description: "Веб-форма для заявок + календарь для техников + простое распределение (ручное)." },
        { step: 3, title: "AI-диспетчер", description: "Claude анализирует тип заявки, расстояние, навыки техников — и предлагает оптимальное распределение." },
        { step: 4, title: "Мобильная версия", description: "PWA или React Native для техников: видеть свои заявки, отмечать выполнение, фотографировать результат." },
        { step: 5, title: "Биллинг + счета", description: "Автоматические счета после завершения работы. Интеграция с QuickBooks / Stripe." },
        { step: 6, title: "Первые клиенты", description: "Cold email 100 HVAC-компаний. Reddit r/HVAC. Facebook-группы подрядчиков. Цель: 10 платящих за 2 месяца." },
      ],
      estimatedTimeline: "MVP за 4 недели, первые клиенты через 8 недель",
      estimatedCost: "$10-20/мес (Supabase + Claude + Twilio)",
    },
  },
  {
    id: 3,
    title: "Автоматический compliance-трекер для SMB",
    description: "Мониторинг регуляторных изменений и автоматические чеклисты для малого бизнеса. GDPR, SOC2, HIPAA.",
    source: "google",
    sourceUrl: "https://news.google.com/articles/abc",
    scoreComposite: 7.6,
    verdict: "BET",
    verdictReason: "Растущий рынок из-за новых регуляций. Нужна валидация: SMB реально покупают compliance-инструменты?",
    status: "scored",
    discoveredAt: "2026-03-09T12:00:00Z",
    scores: { market: 8.0, automation: 7.5, pain: 8.0, competition: 6.5, willingnessToPay: 7.5, margin: 8.0, build: 6.5, timing: 8.5 },
    detail: {
      problem: "Малые бизнесы (5-50 сотрудников) сталкиваются с потоком новых регуляций: GDPR, SOC2, HIPAA, ADA compliance. Консультанты берут $10K+. Крупные инструменты (Vanta, Drata) стоят $10K+/год. SMB остаются без защиты и рискуют штрафами.",
      valueProposition: "AI-трекер, который мониторит новые регуляции в индустрии клиента, генерирует персональные чеклисты и напоминает о дедлайнах. $29/мес вместо $10K за консультанта.",
      targetAudience: "SMB в регулируемых индустриях: здравоохранение, финансы, e-commerce (GDPR). ~2M компаний в США+ЕС.",
      features: [
        "AI-мониторинг новых регуляций по индустрии и региону",
        "Персональные compliance-чеклисты с автоматическими напоминаниями",
        "Шаблоны политик (Privacy Policy, Terms of Service, DPA)",
        "Трекер выполнения: прогресс по каждому стандарту",
        "Email-дайджест: новые требования за неделю",
        "Экспорт отчётов для аудиторов",
      ],
      techStack: ["Next.js", "PostgreSQL", "Claude API", "Resend", "Vercel"],
      pricing: "$29/мес (1 стандарт) / $49/мес (до 3 стандартов) / $99/мес (unlimited)",
      launchSteps: [
        { step: 1, title: "Выбрать одну регуляцию", description: "Начать с GDPR для e-commerce — самый массовый запрос. Один стандарт = меньше сложность MVP." },
        { step: 2, title: "MVP: чеклист + напоминания", description: "Статический чеклист GDPR, персонализированный под тип бизнеса. Email-напоминания о дедлайнах." },
        { step: 3, title: "AI-мониторинг", description: "Claude парсит RSS регуляторов (ICO, EDPB), выделяет изменения, релевантные клиенту." },
        { step: 4, title: "Генерация документов", description: "AI-генерация Privacy Policy, Cookie Policy на основе ответов клиента." },
        { step: 5, title: "Расширение стандартов", description: "Добавить SOC2, HIPAA, PCI DSS. Каждый стандарт = апсейл на более дорогой план." },
        { step: 6, title: "Первые клиенты", description: "SEO: 'GDPR compliance checklist small business'. ProductHunt launch. Cold email Shopify-магазинам." },
      ],
      estimatedTimeline: "MVP за 2 недели, первые клиенты через 4 недели",
      estimatedCost: "$5-10/мес (хостинг + Claude + Resend)",
    },
  },
  {
    id: 4,
    title: "AI-генератор отчётов для арендодателей",
    description: "Автоматические финансовые отчёты, трекинг платежей, налоговые формы для мелких арендодателей (1-5 объектов).",
    source: "reddit",
    sourceUrl: "https://reddit.com/r/landlord/comments/xyz",
    scoreComposite: 7.3,
    verdict: "BET",
    verdictReason: "Недообслуженная ниша — крупные решения от $200/мес, мелким арендодателям нужно что-то за $29/мес.",
    status: "scored",
    discoveredAt: "2026-03-09T08:00:00Z",
    scores: { market: 7.0, automation: 8.0, pain: 7.5, competition: 7.5, willingnessToPay: 7.0, margin: 7.5, build: 7.0, timing: 7.0 },
    detail: {
      problem: "Мелкие арендодатели (1-5 объектов) ведут учёт в Excel или на бумаге. Крупные решения (Yardi, AppFolio) стоят $200-500/мес и рассчитаны на управляющие компании. 11M арендодателей в США, 70% — мелкие.",
      valueProposition: "AI-генератор отчётов: подключи банковский счёт → автоматически категоризируй доходы/расходы → получи готовые отчёты для налоговой и красивый дашборд. $29/мес.",
      targetAudience: "Мелкие арендодатели (1-5 объектов) в США. ~7.7M человек, большинство без профессионального софта.",
      features: [
        "Автоматический импорт транзакций через Plaid",
        "AI-категоризация: аренда, ремонт, страховка, налоги",
        "Генерация Schedule E для IRS (налоговая форма)",
        "Дашборд: доходность каждого объекта, вакантность",
        "Напоминания: срок аренды, страховка, tax deadlines",
        "Экспорт для бухгалтера (PDF, CSV)",
      ],
      techStack: ["Next.js", "Supabase", "Claude API", "Plaid API", "Stripe"],
      pricing: "$29/мес (до 3 объектов) / $49/мес (до 10 объектов) / 14 дней free trial",
      launchSteps: [
        { step: 1, title: "Лендинг + waitlist", description: "SEO под 'landlord expense tracker', 'rental property accounting software'. Таргет: мелкие арендодатели." },
        { step: 2, title: "MVP: ручной ввод + отчёты", description: "Простая форма для ввода доходов/расходов по объектам. AI генерирует месячный отчёт." },
        { step: 3, title: "Plaid интеграция", description: "Автоматический импорт транзакций из банка. AI-категоризация (rent income, repairs, insurance)." },
        { step: 4, title: "Налоговые формы", description: "Генерация Schedule E. Это killer feature — экономит $500+ на бухгалтере." },
        { step: 5, title: "Первые клиенты", description: "Reddit r/landlord, r/realestateinvesting. BiggerPockets форум. Цель: 20 платящих за 3 месяца." },
      ],
      estimatedTimeline: "MVP за 2 недели, Plaid за 4 недели",
      estimatedCost: "$10-20/мес (Supabase + Plaid + Claude)",
    },
  },
  {
    id: 5,
    title: "Планировщик контента для соцсетей",
    description: "Мультиплатформенный постинг с AI-генерацией подписей.",
    source: "devto",
    sourceUrl: "https://dev.to/post/12345",
    scoreComposite: 4.8,
    verdict: "FLIP",
    verdictReason: "Крайне конкурентный рынок. Buffer, Hootsuite доминируют. Возможен только в узкой нише.",
    status: "scored",
    discoveredAt: "2026-03-10T08:00:00Z",
    scores: { market: 6.0, automation: 6.5, pain: 4.0, competition: 2.5, willingnessToPay: 5.5, margin: 5.0, build: 5.0, timing: 4.0 },
  },
  {
    id: 6,
    title: "Крипто-портфолио трекер",
    description: "Отслеживание криптовалютного портфеля с налоговой отчётностью.",
    source: "hackernews",
    sourceUrl: "https://news.ycombinator.com/item?id=2",
    scoreComposite: 3.1,
    verdict: "KILL",
    verdictReason: "Исключённая категория (крипто). Регуляторная сложность слишком высока для автоматизации.",
    status: "rejected",
    discoveredAt: "2026-03-10T09:00:00Z",
    scores: { market: 4.0, automation: 2.0, pain: 3.5, competition: 2.0, willingnessToPay: 4.0, margin: 3.0, build: 3.5, timing: 3.0 },
  },
  {
    id: 7,
    title: "Мониторинг API для инди-разработчиков",
    description: "Простой uptime и latency мониторинг с Slack/Telegram алертами для малых команд.",
    source: "producthunt",
    sourceUrl: "https://producthunt.com/posts/apiwatch",
    scoreComposite: 6.9,
    verdict: "BET",
    verdictReason: "Конкурентный рынок, но сильный recurring revenue. Дифференциация через простоту и цену $9/мес.",
    status: "scored",
    discoveredAt: "2026-03-10T14:00:00Z",
    scores: { market: 7.0, automation: 8.5, pain: 6.5, competition: 4.5, willingnessToPay: 8.0, margin: 7.5, build: 8.0, timing: 5.5 },
    detail: {
      problem: "Инди-разработчики и малые команды (1-5 человек) используют бесплатные решения (UptimeRobot) с ограничениями или дорогие (Datadog $23+/хост). Нет простого инструмента за $9/мес с интеграциями в Slack/Telegram.",
      valueProposition: "Минималистичный мониторинг: добавь URL → получай алерты в Slack/Telegram при даунтайме. Без сложных дашбордов, без enterprise-функций. Просто работает.",
      targetAudience: "Инди-разработчики, фрилансеры, малые SaaS-команды. ~500K потенциальных клиентов.",
      features: [
        "HTTP/HTTPS мониторинг с интервалом 1 минута",
        "Алерты в Slack, Telegram, Discord, email",
        "Простой status page для клиентов",
        "Метрики latency с графиками за 30 дней",
        "SSL-мониторинг: алерт за 14 дней до истечения",
        "API для интеграции с CI/CD",
      ],
      techStack: ["Next.js", "Redis", "BullMQ", "Vercel", "Resend"],
      pricing: "$9/мес (10 мониторов) / $19/мес (50 мониторов) / бесплатно 3 монитора",
      launchSteps: [
        { step: 1, title: "MVP: HTTP checker", description: "Простой сервис: cron каждую минуту делает HTTP-запрос, при ошибке — email. Деплой на Vercel + Upstash Redis." },
        { step: 2, title: "Алерты", description: "Интеграция с Slack (webhook), Telegram (bot API), Discord (webhook). Настройка каналов в дашборде." },
        { step: 3, title: "Status page", description: "Публичная страница статуса для каждого проекта. Поддомен: status.yourapp.com." },
        { step: 4, title: "Запуск", description: "ProductHunt launch + Show HN + Reddit r/webdev, r/SideProject. Бесплатный план привлечёт юзеров." },
      ],
      estimatedTimeline: "MVP за 1 неделю, запуск через 2 недели",
      estimatedCost: "$5/мес (Upstash + Vercel + Resend)",
    },
  },
  {
    id: 8,
    title: "AI-помощник для pest control компаний",
    description: "Автоматическая диспетчеризация, маршрутизация техников, CRM для компаний по борьбе с вредителями.",
    source: "google",
    sourceUrl: "https://news.google.com/articles/def",
    scoreComposite: 7.8,
    verdict: "BET",
    verdictReason: "Blue ocean: 0 специализированных решений. Владельцы бизнесов используют Excel и бумагу. Проверить WTP.",
    status: "scored",
    discoveredAt: "2026-03-11T06:00:00Z",
    scores: { market: 7.0, automation: 8.0, pain: 9.0, competition: 9.5, willingnessToPay: 7.0, margin: 7.5, build: 6.5, timing: 8.0 },
    detail: {
      problem: "Компании по борьбе с вредителями (pest control) управляют бизнесом через бумагу, звонки и Excel. Техники теряются в маршрутах, клиенты ждут звонка часами. Крупные решения (PestRoutes, FieldRoutes) стоят $200+/мес.",
      valueProposition: "AI-помощник для pest control: автоматический приём заявок, оптимальные маршруты для техников, CRM клиентов с историей обработок. $49/мес.",
      targetAudience: "Малые pest control компании (1-10 техников) в США. ~30,000 компаний, рынок $23B.",
      features: [
        "Онлайн-заявки через веб-форму и телефон",
        "AI-маршрутизация: оптимальный порядок визитов",
        "CRM клиентов: адрес, история обработок, тип вредителей",
        "Автоматические напоминания о повторной обработке",
        "Фото до/после от техников",
        "Генерация счетов и приём оплаты",
      ],
      techStack: ["Next.js", "Supabase", "Claude API", "Google Maps API", "Stripe", "Twilio"],
      pricing: "$49/мес (до 5 техников) / $99/мес (до 15 техников)",
      launchSteps: [
        { step: 1, title: "Лендинг + SEO", description: "Таргет: 'pest control software', 'pest control scheduling app'. Лендинг с формой waitlist." },
        { step: 2, title: "MVP: заявки + CRM", description: "Форма для заявок, карточки клиентов, базовое расписание. Без AI — просто работающий CRUD." },
        { step: 3, title: "Маршрутизация", description: "Google Maps API для оптимизации маршрутов. AI-рекомендации по расписанию." },
        { step: 4, title: "Мобильная версия", description: "PWA для техников: текущие заявки, навигация, фото результатов." },
        { step: 5, title: "Первые клиенты", description: "Cold email 200 pest control компаний. Facebook-группы. Местные бизнес-ассоциации." },
      ],
      estimatedTimeline: "MVP за 3 недели, первые клиенты через 6 недель",
      estimatedCost: "$15-25/мес (Supabase + Maps + Twilio)",
    },
  },
  {
    id: 9,
    title: "Универсальный AI-чатбот для поддержки",
    description: "Ещё один чатбот на базе LLM для автоматизации клиентской поддержки.",
    source: "devto",
    sourceUrl: "https://dev.to/post/67890",
    scoreComposite: 3.8,
    verdict: "KILL",
    verdictReason: "Перенасыщенный рынок. 500+ решений. 90% AI-обёрток проваливаются. Нет дифференциации.",
    status: "rejected",
    discoveredAt: "2026-03-11T07:00:00Z",
    scores: { market: 5.0, automation: 4.0, pain: 3.0, competition: 1.5, willingnessToPay: 4.5, margin: 3.5, build: 5.5, timing: 3.5 },
  },
  {
    id: 10,
    title: "Аналитика для Shopify-магазинов",
    description: "Упрощённая аналитика продаж с AI-рекомендациями для мелких Shopify-магазинов.",
    source: "youtube",
    sourceUrl: "https://youtube.com/watch?v=abc123",
    scoreComposite: 5.9,
    verdict: "FLIP",
    verdictReason: "Рынок есть, но много конкурентов (Triple Whale, Lifetimely). Пересмотреть через 2 недели — возможна узкая ниша.",
    status: "scored",
    discoveredAt: "2026-03-11T09:00:00Z",
    scores: { market: 7.5, automation: 7.0, pain: 5.5, competition: 3.5, willingnessToPay: 7.0, margin: 6.0, build: 6.0, timing: 5.0 },
  },
];

export const mockDailyStats: DailyStats[] = [
  { date: "2026-03-05", totalFound: 34, totalFiltered: 18, totalScored: 12 },
  { date: "2026-03-06", totalFound: 28, totalFiltered: 15, totalScored: 10 },
  { date: "2026-03-07", totalFound: 41, totalFiltered: 22, totalScored: 15 },
  { date: "2026-03-08", totalFound: 37, totalFiltered: 19, totalScored: 14 },
  { date: "2026-03-09", totalFound: 45, totalFiltered: 24, totalScored: 18 },
  { date: "2026-03-10", totalFound: 32, totalFiltered: 17, totalScored: 11 },
  { date: "2026-03-11", totalFound: 39, totalFiltered: 21, totalScored: 16 },
];

export const mockCosts: CostEntry[] = [
  { month: "2026-01", costUsd: 0.52, tokensInput: 120000, tokensOutput: 45000 },
  { month: "2026-02", costUsd: 0.71, tokensInput: 165000, tokensOutput: 62000 },
  { month: "2026-03", costUsd: 0.78, tokensInput: 180000, tokensOutput: 68000 },
];
